[project]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Geometric algebra."
name = "infrared"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"
license = "MIT"

[tasks]
bump = "bash scripts/bump.sh"
build = "bash scripts/build.sh"
test = { cmd = "bash scripts/test.sh", depends-on = ["build"] }
temp = "mojo temp.mojo"
format = "mojo format -l 100 src"

[dependencies]
max = "==24.6.0.dev2024100605"
